main = ".worker-next/index.mjs"
name = "cloak-feed"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
experimental_assets = { directory = ".worker-next/assets", binding = "ASSETS" }